spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/payment
    username: root
    password: 1234

  thymeleaf:
    cache: false

PSP:
  toss:
    secretKey: test_sk_kYG57Eba3GjK67ZgKDD98pWDOxmA
    url: https://api.tosspayments.com